version: '3.7'

services:
  # App backend service
  app-server:
    container_name: api-myblog
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

  # Frontend Service
  app-client:
    container_name: client-myblog
    build:
      context: client
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "8082:80"
    restart: always