apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: myblog-api
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
