# Configuração do registry para k3s
# Copiar para: /etc/rancher/k3s/registries.yaml em cada node
configs:
  "registry.lab.home":
    tls:
      ca_file: /home/dell/workspace/infra/step-ca/root_ca.crt
