# Spring and Datasource
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  logging:
    level:
      org.springframework.boot: DEBUG
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:blog
    username: sa
    password: '123'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
    settings:
      web-allow-others: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/specific/h2
    placeholder-replacement: false
    depends-on: entityManagerFactory
    log-sql: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
