INSERT INTO NEWS(title, date, author, content) VALUES('What is Lorem Ipsum?', '2021-09-01 12:00:00.016952', 'Amanda Waller', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus vel justo eu ultrices. Vivamus ac faucibus erat. Sed vulputate eleifend tristique. Integer rhoncus metus quam, a aliquam urna posuere id. Vivamus molestie a tellus non tincidunt. Nam quis nisi sed turpis tristique ornare. Morbi sagittis eu dui eu commodo. Sed vulputate porta elit eget sagittis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ac urna ut leo ultrices sollicitudin et vel felis.

Proin vel aliquam magna, sit amet tincidunt erat. Suspendisse ornare sollicitudin lorem. Nulla volutpat turpis ac justo tincidunt, at placerat nisi euismod. Morbi congue fermentum nulla a porttitor. Etiam vulputate, odio a laoreet finibus, nisl mauris vulputate leo, vitae lobortis lorem ligula nec tortor. Aliquam nec aliquet nibh, malesuada elementum urna. Etiam tempor justo tincidunt tellus euismod, quis dictum magna ornare. Aenean in facilisis erat, non posuere odio. Aliquam in congue magna. Nulla gravida dolor vitae neque vehicula, efficitur malesuada nunc luctus.

Mauris semper, est ut placerat congue, libero turpis eleifend nibh, quis commodo leo augue vel elit. Etiam tristique elit non ex pellentesque blandit vel eget lectus. Nulla maximus, est sed dapibus maximus, nibh felis ullamcorper erat, quis volutpat ligula neque iaculis sem. Nullam sed molestie tortor. Duis nec sollicitudin dolor. Vivamus facilisis pellentesque magna, eu aliquam turpis ultricies et. Fusce blandit sed orci quis malesuada. In ullamcorper elementum quam, quis tristique lacus tempus ac.

Donec facilisis maximus augue, vel fermentum tortor rhoncus sed. Phasellus placerat nibh velit, ut eleifend lectus lacinia vel. Phasellus congue tempus posuere. Nulla scelerisque accumsan justo quis venenatis. Integer at odio et quam iaculis vulputate. Aenean posuere magna tincidunt ipsum euismod rhoncus. Donec pulvinar, enim at suscipit mattis, ligula mauris convallis justo, vel varius ipsum nunc ac lectus. Quisque vulputate velit eu porttitor posuere.

Vestibulum laoreet odio id magna dapibus, non molestie enim consectetur. Aenean suscipit ligula tellus, ac egestas erat varius id. Aenean leo lorem, finibus nec tincidunt vitae, viverra vitae nisl. Fusce at tellus hendrerit, vestibulum leo vitae, tincidunt felis. Nam semper mauris a mauris porta posuere. Sed at nunc id orci dictum venenatis. Pellentesque eget lobortis magna. Praesent porta nunc quis dapibus vulputate. Nam semper ipsum id lacus tempus, vel accumsan justo feugiat. Maecenas volutpat malesuada interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin eu nunc id arcu varius dapibus. Suspendisse eu dictum tortor. Maecenas volutpat sagittis justo nec lobortis. Vivamus tempus auctor consectetur. Curabitur lacinia vitae velit ut venenatis.

Vivamus ac mattis lorem. Pellentesque blandit ultricies velit, eget aliquam leo eleifend ac. Morbi ultrices aliquet imperdiet. Vestibulum eu finibus elit, in gravida lectus. Phasellus volutpat finibus augue non rhoncus. Donec et imperdiet quam. Praesent sed congue erat, convallis congue tortor. Curabitur sodales risus ante, sit amet sagittis eros commodo eu. Aliquam vulputate consequat mauris, sollicitudin imperdiet neque vulputate eget. Aliquam faucibus tempus fringilla. Integer tempor libero at lorem vestibulum, ut scelerisque enim imperdiet. Duis vitae viverra quam, vitae accumsan urna.

Curabitur eget lacinia nibh. Duis mattis non dolor vitae maximus. Fusce eget dui fringilla, dictum justo et, convallis mauris. Nulla fringilla placerat neque et euismod. Phasellus ac eros commodo, ultricies est et, aliquet nunc. Sed sagittis lorem vel eros faucibus, sed scelerisque tortor hendrerit. Nam elit eros, eleifend ac orci in, bibendum elementum orci. In at luctus nunc.

Nam ultricies odio ac fringilla dignissim. Etiam a enim eu lectus auctor molestie eu et quam. Proin lacinia porta ante, id porta quam convallis quis. Etiam aliquam dolor diam, a mollis mi maximus id. Phasellus rhoncus, lorem a pharetra semper, ligula sapien pellentesque quam, eu gravida eros dui ac sem. Integer gravida ornare placerat. Pellentesque vel turpis a massa vulputate imperdiet nec nec enim. Maecenas dignissim sed risus et pretium. Nunc vulputate augue arcu, facilisis congue mi vulputate ut. Phasellus ut mauris orci. Aenean ut tincidunt odio. Morbi id est et nisi ultrices ullamcorper ornare malesuada nisl. Praesent nec ligula ac lacus laoreet gravida. Donec nulla ante, placerat a mi at, rhoncus mattis ligula.

Nam semper ex vitae dapibus placerat. Nulla ipsum eros, condimentum posuere diam feugiat, pellentesque blandit dolor. Donec eleifend arcu eget molestie maximus. Nulla id arcu sit amet mauris sagittis molestie. In varius nunc sit amet ultrices cursus. In dictum lacus vel vestibulum lobortis. Donec fermentum blandit aliquam. Mauris vel mauris sed lacus maximus pellentesque. Quisque quis nunc ac est rutrum pellentesque.

Sed imperdiet mi sit amet nulla rhoncus gravida. Sed porta interdum elit, et maximus neque malesuada consequat. Cras porttitor sodales nulla in commodo. Vivamus massa nunc, convallis eget dictum in, faucibus eget felis. Morbi egestas vehicula tortor, sed dictum nulla malesuada vitae. Donec consequat vitae magna sed efficitur. In tincidunt sagittis quam, at bibendum neque hendrerit vel. Integer sollicitudin eu quam ac cursus. Sed venenatis mauris elit, quis rutrum neque sollicitudin id. Sed sed sapien aliquet, interdum libero vel, ultrices justo. Curabitur et sapien tristique, rhoncus enim nec, sollicitudin elit. Vivamus sit amet dictum lorem. Donec porttitor ante urna, ac sodales dui pretium et. Curabitur vel auctor justo. Aliquam ullamcorper justo volutpat lorem scelerisque gravida.

Donec diam quam, convallis et arcu eget, dapibus iaculis ligula. Proin suscipit tortor id porta mattis. Nullam suscipit dui convallis tempor maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin velit justo, iaculis mattis mattis at, hendrerit quis turpis. Proin a bibendum purus. Maecenas condimentum, nisl id congue mollis, mi elit accumsan purus, et dictum felis odio ut augue. Etiam aliquet nisi a libero finibus imperdiet. Nullam tempor turpis ac arcu feugiat cursus. Maecenas non diam elementum nibh porta imperdiet.

Suspendisse sapien lorem, tincidunt et metus at, viverra blandit mi. Duis enim odio, placerat ac tincidunt a, lobortis nec ligula. Sed sollicitudin purus orci, eu fringilla neque imperdiet eu. In hac habitasse platea dictumst. Aliquam convallis, magna a interdum lobortis, libero risus auctor augue, vitae convallis nulla diam id ante. Nullam lorem enim, tincidunt a sollicitudin et, tristique quis elit. Morbi eu eros eget eros finibus imperdiet quis id odio. Praesent euismod leo vitae odio scelerisque, eu tempor nisl vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas placerat, turpis at egestas elementum, augue arcu dictum turpis, id molestie ipsum ante et nibh. Vivamus eget tincidunt purus. Mauris sagittis augue odio, sed varius quam vulputate at. Etiam orci elit, bibendum eget neque nec, scelerisque rutrum est. Proin ut ipsum ipsum.

Proin a hendrerit nisl. Vivamus sodales ante a arcu rutrum posuere. Cras mauris mi, rhoncus sit amet molestie in, ornare id mauris. Donec at elementum tellus, vel accumsan velit. Vestibulum tellus metus, lobortis vel ex luctus, iaculis pulvinar orci. Phasellus ornare lectus at velit dapibus consequat. Quisque eu dapibus orci. Nullam at nunc sit amet metus finibus dapibus et eget ligula. Etiam venenatis venenatis diam id finibus. Etiam ultrices nibh at ex aliquet auctor fermentum eu lorem. Nulla vel enim luctus turpis vehicula dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed mauris est, congue vitae sollicitudin ac, pharetra vel enim. Fusce fringilla dolor in quam pellentesque fermentum. Maecenas at purus nisl. Maecenas ut ex ultricies, dictum tortor quis, fermentum turpis. Ut massa nunc, volutpat vel feugiat eu, scelerisque nec eros. Duis magna leo, ornare quis rhoncus vitae, molestie eu sem. Suspendisse commodo mi id maximus pulvinar. Nulla iaculis lacinia leo sed luctus. Maecenas ultricies leo eget nulla aliquam, quis luctus sapien molestie. Donec consectetur velit in suscipit tincidunt. Donec consequat tellus sit amet viverra egestas.

Sed luctus odio quis lorem consectetur, non porttitor elit congue. Maecenas tempor est ante, sed finibus quam placerat id. In dictum luctus magna, eget facilisis massa fringilla id. Curabitur commodo elit vel dapibus iaculis. Sed tristique nulla mi, id aliquam tortor sodales sit amet. Pellentesque non aliquam mauris. Pellentesque efficitur, erat sit amet sodales condimentum, ante lorem rhoncus arcu, vitae placerat dui velit quis diam. Sed at dictum nibh. Quisque et elit tellus. Phasellus eu pulvinar urna, at varius augue. Sed fermentum neque libero. Sed orci justo, ultrices quis risus vitae, egestas convallis lectus. Praesent rutrum est at elit posuere, id volutpat nisl rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque condimentum quis massa ac congue.

Mauris sodales porta ipsum. Praesent tincidunt consectetur orci nec eleifend. Etiam facilisis eros ac erat rutrum suscipit. Morbi non laoreet ipsum. Ut et porta odio. Vestibulum ac nisi blandit, elementum mauris quis, placerat enim. Sed hendrerit lacinia nisi in fermentum. Nullam condimentum accumsan leo eget scelerisque. Nullam posuere lorem nec nibh congue commodo.

Cras eu ornare ipsum. Cras sit amet eros id metus facilisis fringilla vitae in tortor. Nunc tincidunt sem eros, ac iaculis magna pretium eu. In dapibus luctus massa in imperdiet. In euismod sodales mauris et porta. Sed dapibus nunc sit amet arcu faucibus, in bibendum velit pharetra. Donec eu sollicitudin tortor. Sed ac iaculis felis, vitae euismod ipsum. Nunc molestie leo odio, vel ornare dui ultricies sed. Sed suscipit dignissim auctor.

Proin quis tincidunt ipsum, vel sollicitudin tortor. Nulla ullamcorper lobortis molestie. Aliquam at arcu tortor. Donec bibendum turpis sed leo dapibus, ut pellentesque mi sodales. Vestibulum quis diam mauris. Maecenas at est volutpat tellus gravida molestie id eu eros. Pellentesque aliquet congue risus at luctus.

Pellentesque eu nunc vitae velit varius scelerisque. Pellentesque eu porta enim. Vivamus quis neque nibh. Nunc sed lacus et ligula ornare sagittis. Aliquam dignissim consequat velit, ut porta neque pellentesque at. Sed eget finibus elit, vel venenatis eros. Nullam ornare iaculis arcu vitae consectetur. Suspendisse ut lobortis libero. Maecenas libero orci, mollis sed ligula et, lobortis congue libero. Donec aliquet neque non velit pretium euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Pellentesque cursus nec massa eget fringilla. Sed ut placerat tellus. Vestibulum et efficitur mauris, vel aliquam libero. Pellentesque fringilla urna et augue aliquet convallis eget in arcu. Sed vel tortor in tortor pretium commodo. Integer tincidunt finibus sem vitae varius. Sed viverra sagittis mi.

Aenean sit amet nisl ultrices, aliquet libero quis, elementum est. Etiam consequat, risus at dictum iaculis, risus urna bibendum justo, at efficitur risus felis sed urna. Donec varius vehicula urna, vitae feugiat ante lacinia a. Aenean tristique nisi vel magna venenatis efficitur. Vivamus porttitor arcu eget lectus scelerisque, eget porta elit tincidunt. Vivamus sollicitudin eget ligula vel dignissim. Quisque commodo sapien vitae felis ultrices elementum.

Etiam faucibus tincidunt nisl, sit amet gravida urna eleifend quis. Fusce euismod viverra tortor, at vehicula nulla accumsan quis. Duis convallis leo ut scelerisque faucibus. Nam sollicitudin finibus lectus sit amet condimentum. Nulla commodo vestibulum facilisis. Nunc hendrerit, massa id ultricies porta, enim tellus pulvinar sem, ut varius est massa eu justo. Aliquam suscipit, massa in faucibus tempor, erat est ultricies lorem, vel cursus mauris lectus nec nulla. Etiam sed nibh in turpis vestibulum luctus. Mauris porttitor at augue eu pharetra. Maecenas placerat mollis urna, eu scelerisque quam molestie sed. Proin at arcu arcu. Mauris nec est eget metus commodo interdum. Suspendisse facilisis turpis tellus, vitae venenatis nulla iaculis eu. Praesent nec tristique felis. Nulla facilisi.

Pellentesque varius et mauris sit amet dictum. Cras eleifend blandit viverra. Curabitur lorem felis, faucibus non posuere ac, ornare at ante. Mauris nec orci augue. Quisque tristique maximus orci at lacinia. In sodales tempor purus, sodales pharetra est suscipit vitae. Donec sed efficitur sem. Vivamus ut leo odio. Curabitur auctor urna ut egestas imperdiet. Nullam consequat accumsan libero, at commodo elit sollicitudin et.

Vestibulum risus urna, interdum et massa congue, gravida elementum nibh. Donec vitae scelerisque ante. Aliquam in diam vel purus tincidunt tincidunt lacinia eget nunc. Cras auctor elit libero. Suspendisse sed scelerisque odio. Cras ut euismod ex. Nam molestie euismod urna. Pellentesque molestie maximus dictum. Donec nisl lacus, vehicula nec lectus et, aliquet rhoncus libero. Vestibulum ultricies velit quis odio pulvinar, eu malesuada purus aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec faucibus nunc id pharetra egestas. Morbi elementum libero ut quam convallis vestibulum. Mauris cursus dui dolor, id vulputate ante convallis et. Praesent lobortis convallis cursus.

Nulla non tincidunt urna. Aliquam vel vestibulum urna. Nunc mattis, ante eleifend finibus ornare, sapien nulla facilisis ante, non mattis nisl risus quis dolor. Sed efficitur rhoncus quam sit amet tincidunt. Donec vitae imperdiet justo. Fusce eu ligula id nisi lobortis suscipit. Praesent iaculis ac nunc sed aliquet. Donec luctus condimentum dapibus. Morbi porta, arcu at aliquet pretium, purus tortor varius nisl, id tristique urna quam non enim. Nunc libero nisi, congue eget placerat vitae, ultricies nec arcu. Sed vulputate, erat in volutpat varius, urna metus elementum turpis, mollis posuere felis nulla ut erat. In faucibus, lectus quis posuere sagittis, urna nunc placerat mauris, eu pellentesque quam lorem id odio.');


INSERT INTO NEWS(title, date, author, content) VALUES('Where does it come from?', '2021-09-09 12:00:00.016952', 'Capitan America', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus vel justo eu ultrices. Vivamus ac faucibus erat. Sed vulputate eleifend tristique. Integer rhoncus metus quam, a aliquam urna posuere id. Vivamus molestie a tellus non tincidunt. Nam quis nisi sed turpis tristique ornare. Morbi sagittis eu dui eu commodo. Sed vulputate porta elit eget sagittis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ac urna ut leo ultrices sollicitudin et vel felis.

Proin vel aliquam magna, sit amet tincidunt erat. Suspendisse ornare sollicitudin lorem. Nulla volutpat turpis ac justo tincidunt, at placerat nisi euismod. Morbi congue fermentum nulla a porttitor. Etiam vulputate, odio a laoreet finibus, nisl mauris vulputate leo, vitae lobortis lorem ligula nec tortor. Aliquam nec aliquet nibh, malesuada elementum urna. Etiam tempor justo tincidunt tellus euismod, quis dictum magna ornare. Aenean in facilisis erat, non posuere odio. Aliquam in congue magna. Nulla gravida dolor vitae neque vehicula, efficitur malesuada nunc luctus.

Mauris semper, est ut placerat congue, libero turpis eleifend nibh, quis commodo leo augue vel elit. Etiam tristique elit non ex pellentesque blandit vel eget lectus. Nulla maximus, est sed dapibus maximus, nibh felis ullamcorper erat, quis volutpat ligula neque iaculis sem. Nullam sed molestie tortor. Duis nec sollicitudin dolor. Vivamus facilisis pellentesque magna, eu aliquam turpis ultricies et. Fusce blandit sed orci quis malesuada. In ullamcorper elementum quam, quis tristique lacus tempus ac.

Donec facilisis maximus augue, vel fermentum tortor rhoncus sed. Phasellus placerat nibh velit, ut eleifend lectus lacinia vel. Phasellus congue tempus posuere. Nulla scelerisque accumsan justo quis venenatis. Integer at odio et quam iaculis vulputate. Aenean posuere magna tincidunt ipsum euismod rhoncus. Donec pulvinar, enim at suscipit mattis, ligula mauris convallis justo, vel varius ipsum nunc ac lectus. Quisque vulputate velit eu porttitor posuere.

Vestibulum laoreet odio id magna dapibus, non molestie enim consectetur. Aenean suscipit ligula tellus, ac egestas erat varius id. Aenean leo lorem, finibus nec tincidunt vitae, viverra vitae nisl. Fusce at tellus hendrerit, vestibulum leo vitae, tincidunt felis. Nam semper mauris a mauris porta posuere. Sed at nunc id orci dictum venenatis. Pellentesque eget lobortis magna. Praesent porta nunc quis dapibus vulputate. Nam semper ipsum id lacus tempus, vel accumsan justo feugiat. Maecenas volutpat malesuada interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin eu nunc id arcu varius dapibus. Suspendisse eu dictum tortor. Maecenas volutpat sagittis justo nec lobortis. Vivamus tempus auctor consectetur. Curabitur lacinia vitae velit ut venenatis.

Vivamus ac mattis lorem. Pellentesque blandit ultricies velit, eget aliquam leo eleifend ac. Morbi ultrices aliquet imperdiet. Vestibulum eu finibus elit, in gravida lectus. Phasellus volutpat finibus augue non rhoncus. Donec et imperdiet quam. Praesent sed congue erat, convallis congue tortor. Curabitur sodales risus ante, sit amet sagittis eros commodo eu. Aliquam vulputate consequat mauris, sollicitudin imperdiet neque vulputate eget. Aliquam faucibus tempus fringilla. Integer tempor libero at lorem vestibulum, ut scelerisque enim imperdiet. Duis vitae viverra quam, vitae accumsan urna.

Curabitur eget lacinia nibh. Duis mattis non dolor vitae maximus. Fusce eget dui fringilla, dictum justo et, convallis mauris. Nulla fringilla placerat neque et euismod. Phasellus ac eros commodo, ultricies est et, aliquet nunc. Sed sagittis lorem vel eros faucibus, sed scelerisque tortor hendrerit. Nam elit eros, eleifend ac orci in, bibendum elementum orci. In at luctus nunc.

Nam ultricies odio ac fringilla dignissim. Etiam a enim eu lectus auctor molestie eu et quam. Proin lacinia porta ante, id porta quam convallis quis. Etiam aliquam dolor diam, a mollis mi maximus id. Phasellus rhoncus, lorem a pharetra semper, ligula sapien pellentesque quam, eu gravida eros dui ac sem. Integer gravida ornare placerat. Pellentesque vel turpis a massa vulputate imperdiet nec nec enim. Maecenas dignissim sed risus et pretium. Nunc vulputate augue arcu, facilisis congue mi vulputate ut. Phasellus ut mauris orci. Aenean ut tincidunt odio. Morbi id est et nisi ultrices ullamcorper ornare malesuada nisl. Praesent nec ligula ac lacus laoreet gravida. Donec nulla ante, placerat a mi at, rhoncus mattis ligula.

Nam semper ex vitae dapibus placerat. Nulla ipsum eros, condimentum posuere diam feugiat, pellentesque blandit dolor. Donec eleifend arcu eget molestie maximus. Nulla id arcu sit amet mauris sagittis molestie. In varius nunc sit amet ultrices cursus. In dictum lacus vel vestibulum lobortis. Donec fermentum blandit aliquam. Mauris vel mauris sed lacus maximus pellentesque. Quisque quis nunc ac est rutrum pellentesque.

Sed imperdiet mi sit amet nulla rhoncus gravida. Sed porta interdum elit, et maximus neque malesuada consequat. Cras porttitor sodales nulla in commodo. Vivamus massa nunc, convallis eget dictum in, faucibus eget felis. Morbi egestas vehicula tortor, sed dictum nulla malesuada vitae. Donec consequat vitae magna sed efficitur. In tincidunt sagittis quam, at bibendum neque hendrerit vel. Integer sollicitudin eu quam ac cursus. Sed venenatis mauris elit, quis rutrum neque sollicitudin id. Sed sed sapien aliquet, interdum libero vel, ultrices justo. Curabitur et sapien tristique, rhoncus enim nec, sollicitudin elit. Vivamus sit amet dictum lorem. Donec porttitor ante urna, ac sodales dui pretium et. Curabitur vel auctor justo. Aliquam ullamcorper justo volutpat lorem scelerisque gravida.

Donec diam quam, convallis et arcu eget, dapibus iaculis ligula. Proin suscipit tortor id porta mattis. Nullam suscipit dui convallis tempor maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin velit justo, iaculis mattis mattis at, hendrerit quis turpis. Proin a bibendum purus. Maecenas condimentum, nisl id congue mollis, mi elit accumsan purus, et dictum felis odio ut augue. Etiam aliquet nisi a libero finibus imperdiet. Nullam tempor turpis ac arcu feugiat cursus. Maecenas non diam elementum nibh porta imperdiet.

Suspendisse sapien lorem, tincidunt et metus at, viverra blandit mi. Duis enim odio, placerat ac tincidunt a, lobortis nec ligula. Sed sollicitudin purus orci, eu fringilla neque imperdiet eu. In hac habitasse platea dictumst. Aliquam convallis, magna a interdum lobortis, libero risus auctor augue, vitae convallis nulla diam id ante. Nullam lorem enim, tincidunt a sollicitudin et, tristique quis elit. Morbi eu eros eget eros finibus imperdiet quis id odio. Praesent euismod leo vitae odio scelerisque, eu tempor nisl vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas placerat, turpis at egestas elementum, augue arcu dictum turpis, id molestie ipsum ante et nibh. Vivamus eget tincidunt purus. Mauris sagittis augue odio, sed varius quam vulputate at. Etiam orci elit, bibendum eget neque nec, scelerisque rutrum est. Proin ut ipsum ipsum.

Proin a hendrerit nisl. Vivamus sodales ante a arcu rutrum posuere. Cras mauris mi, rhoncus sit amet molestie in, ornare id mauris. Donec at elementum tellus, vel accumsan velit. Vestibulum tellus metus, lobortis vel ex luctus, iaculis pulvinar orci. Phasellus ornare lectus at velit dapibus consequat. Quisque eu dapibus orci. Nullam at nunc sit amet metus finibus dapibus et eget ligula. Etiam venenatis venenatis diam id finibus. Etiam ultrices nibh at ex aliquet auctor fermentum eu lorem. Nulla vel enim luctus turpis vehicula dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed mauris est, congue vitae sollicitudin ac, pharetra vel enim. Fusce fringilla dolor in quam pellentesque fermentum. Maecenas at purus nisl. Maecenas ut ex ultricies, dictum tortor quis, fermentum turpis. Ut massa nunc, volutpat vel feugiat eu, scelerisque nec eros. Duis magna leo, ornare quis rhoncus vitae, molestie eu sem. Suspendisse commodo mi id maximus pulvinar. Nulla iaculis lacinia leo sed luctus. Maecenas ultricies leo eget nulla aliquam, quis luctus sapien molestie. Donec consectetur velit in suscipit tincidunt. Donec consequat tellus sit amet viverra egestas.

Sed luctus odio quis lorem consectetur, non porttitor elit congue. Maecenas tempor est ante, sed finibus quam placerat id. In dictum luctus magna, eget facilisis massa fringilla id. Curabitur commodo elit vel dapibus iaculis. Sed tristique nulla mi, id aliquam tortor sodales sit amet. Pellentesque non aliquam mauris. Pellentesque efficitur, erat sit amet sodales condimentum, ante lorem rhoncus arcu, vitae placerat dui velit quis diam. Sed at dictum nibh. Quisque et elit tellus. Phasellus eu pulvinar urna, at varius augue. Sed fermentum neque libero. Sed orci justo, ultrices quis risus vitae, egestas convallis lectus. Praesent rutrum est at elit posuere, id volutpat nisl rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque condimentum quis massa ac congue.

Mauris sodales porta ipsum. Praesent tincidunt consectetur orci nec eleifend. Etiam facilisis eros ac erat rutrum suscipit. Morbi non laoreet ipsum. Ut et porta odio. Vestibulum ac nisi blandit, elementum mauris quis, placerat enim. Sed hendrerit lacinia nisi in fermentum. Nullam condimentum accumsan leo eget scelerisque. Nullam posuere lorem nec nibh congue commodo.

Cras eu ornare ipsum. Cras sit amet eros id metus facilisis fringilla vitae in tortor. Nunc tincidunt sem eros, ac iaculis magna pretium eu. In dapibus luctus massa in imperdiet. In euismod sodales mauris et porta. Sed dapibus nunc sit amet arcu faucibus, in bibendum velit pharetra. Donec eu sollicitudin tortor. Sed ac iaculis felis, vitae euismod ipsum. Nunc molestie leo odio, vel ornare dui ultricies sed. Sed suscipit dignissim auctor.

Proin quis tincidunt ipsum, vel sollicitudin tortor. Nulla ullamcorper lobortis molestie. Aliquam at arcu tortor. Donec bibendum turpis sed leo dapibus, ut pellentesque mi sodales. Vestibulum quis diam mauris. Maecenas at est volutpat tellus gravida molestie id eu eros. Pellentesque aliquet congue risus at luctus.

Pellentesque eu nunc vitae velit varius scelerisque. Pellentesque eu porta enim. Vivamus quis neque nibh. Nunc sed lacus et ligula ornare sagittis. Aliquam dignissim consequat velit, ut porta neque pellentesque at. Sed eget finibus elit, vel venenatis eros. Nullam ornare iaculis arcu vitae consectetur. Suspendisse ut lobortis libero. Maecenas libero orci, mollis sed ligula et, lobortis congue libero. Donec aliquet neque non velit pretium euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Pellentesque cursus nec massa eget fringilla. Sed ut placerat tellus. Vestibulum et efficitur mauris, vel aliquam libero. Pellentesque fringilla urna et augue aliquet convallis eget in arcu. Sed vel tortor in tortor pretium commodo. Integer tincidunt finibus sem vitae varius. Sed viverra sagittis mi.

Aenean sit amet nisl ultrices, aliquet libero quis, elementum est. Etiam consequat, risus at dictum iaculis, risus urna bibendum justo, at efficitur risus felis sed urna. Donec varius vehicula urna, vitae feugiat ante lacinia a. Aenean tristique nisi vel magna venenatis efficitur. Vivamus porttitor arcu eget lectus scelerisque, eget porta elit tincidunt. Vivamus sollicitudin eget ligula vel dignissim. Quisque commodo sapien vitae felis ultrices elementum.

Etiam faucibus tincidunt nisl, sit amet gravida urna eleifend quis. Fusce euismod viverra tortor, at vehicula nulla accumsan quis. Duis convallis leo ut scelerisque faucibus. Nam sollicitudin finibus lectus sit amet condimentum. Nulla commodo vestibulum facilisis. Nunc hendrerit, massa id ultricies porta, enim tellus pulvinar sem, ut varius est massa eu justo. Aliquam suscipit, massa in faucibus tempor, erat est ultricies lorem, vel cursus mauris lectus nec nulla. Etiam sed nibh in turpis vestibulum luctus. Mauris porttitor at augue eu pharetra. Maecenas placerat mollis urna, eu scelerisque quam molestie sed. Proin at arcu arcu. Mauris nec est eget metus commodo interdum. Suspendisse facilisis turpis tellus, vitae venenatis nulla iaculis eu. Praesent nec tristique felis. Nulla facilisi.

Pellentesque varius et mauris sit amet dictum. Cras eleifend blandit viverra. Curabitur lorem felis, faucibus non posuere ac, ornare at ante. Mauris nec orci augue. Quisque tristique maximus orci at lacinia. In sodales tempor purus, sodales pharetra est suscipit vitae. Donec sed efficitur sem. Vivamus ut leo odio. Curabitur auctor urna ut egestas imperdiet. Nullam consequat accumsan libero, at commodo elit sollicitudin et.

Vestibulum risus urna, interdum et massa congue, gravida elementum nibh. Donec vitae scelerisque ante. Aliquam in diam vel purus tincidunt tincidunt lacinia eget nunc. Cras auctor elit libero. Suspendisse sed scelerisque odio. Cras ut euismod ex. Nam molestie euismod urna. Pellentesque molestie maximus dictum. Donec nisl lacus, vehicula nec lectus et, aliquet rhoncus libero. Vestibulum ultricies velit quis odio pulvinar, eu malesuada purus aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec faucibus nunc id pharetra egestas. Morbi elementum libero ut quam convallis vestibulum. Mauris cursus dui dolor, id vulputate ante convallis et. Praesent lobortis convallis cursus.

Nulla non tincidunt urna. Aliquam vel vestibulum urna. Nunc mattis, ante eleifend finibus ornare, sapien nulla facilisis ante, non mattis nisl risus quis dolor. Sed efficitur rhoncus quam sit amet tincidunt. Donec vitae imperdiet justo. Fusce eu ligula id nisi lobortis suscipit. Praesent iaculis ac nunc sed aliquet. Donec luctus condimentum dapibus. Morbi porta, arcu at aliquet pretium, purus tortor varius nisl, id tristique urna quam non enim. Nunc libero nisi, congue eget placerat vitae, ultricies nec arcu. Sed vulputate, erat in volutpat varius, urna metus elementum turpis, mollis posuere felis nulla ut erat. In faucibus, lectus quis posuere sagittis, urna nunc placerat mauris, eu pellentesque quam lorem id odio.');

INSERT INTO NEWS(title, date, author, content) VALUES('Why do we use it?', '2021-09-09 12:00:00.016952', 'Bruce Wayne', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus vel justo eu ultrices. Vivamus ac faucibus erat. Sed vulputate eleifend tristique. Integer rhoncus metus quam, a aliquam urna posuere id. Vivamus molestie a tellus non tincidunt. Nam quis nisi sed turpis tristique ornare. Morbi sagittis eu dui eu commodo. Sed vulputate porta elit eget sagittis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ac urna ut leo ultrices sollicitudin et vel felis.

Proin vel aliquam magna, sit amet tincidunt erat. Suspendisse ornare sollicitudin lorem. Nulla volutpat turpis ac justo tincidunt, at placerat nisi euismod. Morbi congue fermentum nulla a porttitor. Etiam vulputate, odio a laoreet finibus, nisl mauris vulputate leo, vitae lobortis lorem ligula nec tortor. Aliquam nec aliquet nibh, malesuada elementum urna. Etiam tempor justo tincidunt tellus euismod, quis dictum magna ornare. Aenean in facilisis erat, non posuere odio. Aliquam in congue magna. Nulla gravida dolor vitae neque vehicula, efficitur malesuada nunc luctus.

Mauris semper, est ut placerat congue, libero turpis eleifend nibh, quis commodo leo augue vel elit. Etiam tristique elit non ex pellentesque blandit vel eget lectus. Nulla maximus, est sed dapibus maximus, nibh felis ullamcorper erat, quis volutpat ligula neque iaculis sem. Nullam sed molestie tortor. Duis nec sollicitudin dolor. Vivamus facilisis pellentesque magna, eu aliquam turpis ultricies et. Fusce blandit sed orci quis malesuada. In ullamcorper elementum quam, quis tristique lacus tempus ac.

Donec facilisis maximus augue, vel fermentum tortor rhoncus sed. Phasellus placerat nibh velit, ut eleifend lectus lacinia vel. Phasellus congue tempus posuere. Nulla scelerisque accumsan justo quis venenatis. Integer at odio et quam iaculis vulputate. Aenean posuere magna tincidunt ipsum euismod rhoncus. Donec pulvinar, enim at suscipit mattis, ligula mauris convallis justo, vel varius ipsum nunc ac lectus. Quisque vulputate velit eu porttitor posuere.

Vestibulum laoreet odio id magna dapibus, non molestie enim consectetur. Aenean suscipit ligula tellus, ac egestas erat varius id. Aenean leo lorem, finibus nec tincidunt vitae, viverra vitae nisl. Fusce at tellus hendrerit, vestibulum leo vitae, tincidunt felis. Nam semper mauris a mauris porta posuere. Sed at nunc id orci dictum venenatis. Pellentesque eget lobortis magna. Praesent porta nunc quis dapibus vulputate. Nam semper ipsum id lacus tempus, vel accumsan justo feugiat. Maecenas volutpat malesuada interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin eu nunc id arcu varius dapibus. Suspendisse eu dictum tortor. Maecenas volutpat sagittis justo nec lobortis. Vivamus tempus auctor consectetur. Curabitur lacinia vitae velit ut venenatis.

Vivamus ac mattis lorem. Pellentesque blandit ultricies velit, eget aliquam leo eleifend ac. Morbi ultrices aliquet imperdiet. Vestibulum eu finibus elit, in gravida lectus. Phasellus volutpat finibus augue non rhoncus. Donec et imperdiet quam. Praesent sed congue erat, convallis congue tortor. Curabitur sodales risus ante, sit amet sagittis eros commodo eu. Aliquam vulputate consequat mauris, sollicitudin imperdiet neque vulputate eget. Aliquam faucibus tempus fringilla. Integer tempor libero at lorem vestibulum, ut scelerisque enim imperdiet. Duis vitae viverra quam, vitae accumsan urna.

Curabitur eget lacinia nibh. Duis mattis non dolor vitae maximus. Fusce eget dui fringilla, dictum justo et, convallis mauris. Nulla fringilla placerat neque et euismod. Phasellus ac eros commodo, ultricies est et, aliquet nunc. Sed sagittis lorem vel eros faucibus, sed scelerisque tortor hendrerit. Nam elit eros, eleifend ac orci in, bibendum elementum orci. In at luctus nunc.

Nam ultricies odio ac fringilla dignissim. Etiam a enim eu lectus auctor molestie eu et quam. Proin lacinia porta ante, id porta quam convallis quis. Etiam aliquam dolor diam, a mollis mi maximus id. Phasellus rhoncus, lorem a pharetra semper, ligula sapien pellentesque quam, eu gravida eros dui ac sem. Integer gravida ornare placerat. Pellentesque vel turpis a massa vulputate imperdiet nec nec enim. Maecenas dignissim sed risus et pretium. Nunc vulputate augue arcu, facilisis congue mi vulputate ut. Phasellus ut mauris orci. Aenean ut tincidunt odio. Morbi id est et nisi ultrices ullamcorper ornare malesuada nisl. Praesent nec ligula ac lacus laoreet gravida. Donec nulla ante, placerat a mi at, rhoncus mattis ligula.

Nam semper ex vitae dapibus placerat. Nulla ipsum eros, condimentum posuere diam feugiat, pellentesque blandit dolor. Donec eleifend arcu eget molestie maximus. Nulla id arcu sit amet mauris sagittis molestie. In varius nunc sit amet ultrices cursus. In dictum lacus vel vestibulum lobortis. Donec fermentum blandit aliquam. Mauris vel mauris sed lacus maximus pellentesque. Quisque quis nunc ac est rutrum pellentesque.

Sed imperdiet mi sit amet nulla rhoncus gravida. Sed porta interdum elit, et maximus neque malesuada consequat. Cras porttitor sodales nulla in commodo. Vivamus massa nunc, convallis eget dictum in, faucibus eget felis. Morbi egestas vehicula tortor, sed dictum nulla malesuada vitae. Donec consequat vitae magna sed efficitur. In tincidunt sagittis quam, at bibendum neque hendrerit vel. Integer sollicitudin eu quam ac cursus. Sed venenatis mauris elit, quis rutrum neque sollicitudin id. Sed sed sapien aliquet, interdum libero vel, ultrices justo. Curabitur et sapien tristique, rhoncus enim nec, sollicitudin elit. Vivamus sit amet dictum lorem. Donec porttitor ante urna, ac sodales dui pretium et. Curabitur vel auctor justo. Aliquam ullamcorper justo volutpat lorem scelerisque gravida.

Donec diam quam, convallis et arcu eget, dapibus iaculis ligula. Proin suscipit tortor id porta mattis. Nullam suscipit dui convallis tempor maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin velit justo, iaculis mattis mattis at, hendrerit quis turpis. Proin a bibendum purus. Maecenas condimentum, nisl id congue mollis, mi elit accumsan purus, et dictum felis odio ut augue. Etiam aliquet nisi a libero finibus imperdiet. Nullam tempor turpis ac arcu feugiat cursus. Maecenas non diam elementum nibh porta imperdiet.

Suspendisse sapien lorem, tincidunt et metus at, viverra blandit mi. Duis enim odio, placerat ac tincidunt a, lobortis nec ligula. Sed sollicitudin purus orci, eu fringilla neque imperdiet eu. In hac habitasse platea dictumst. Aliquam convallis, magna a interdum lobortis, libero risus auctor augue, vitae convallis nulla diam id ante. Nullam lorem enim, tincidunt a sollicitudin et, tristique quis elit. Morbi eu eros eget eros finibus imperdiet quis id odio. Praesent euismod leo vitae odio scelerisque, eu tempor nisl vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas placerat, turpis at egestas elementum, augue arcu dictum turpis, id molestie ipsum ante et nibh. Vivamus eget tincidunt purus. Mauris sagittis augue odio, sed varius quam vulputate at. Etiam orci elit, bibendum eget neque nec, scelerisque rutrum est. Proin ut ipsum ipsum.

Proin a hendrerit nisl. Vivamus sodales ante a arcu rutrum posuere. Cras mauris mi, rhoncus sit amet molestie in, ornare id mauris. Donec at elementum tellus, vel accumsan velit. Vestibulum tellus metus, lobortis vel ex luctus, iaculis pulvinar orci. Phasellus ornare lectus at velit dapibus consequat. Quisque eu dapibus orci. Nullam at nunc sit amet metus finibus dapibus et eget ligula. Etiam venenatis venenatis diam id finibus. Etiam ultrices nibh at ex aliquet auctor fermentum eu lorem. Nulla vel enim luctus turpis vehicula dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed mauris est, congue vitae sollicitudin ac, pharetra vel enim. Fusce fringilla dolor in quam pellentesque fermentum. Maecenas at purus nisl. Maecenas ut ex ultricies, dictum tortor quis, fermentum turpis. Ut massa nunc, volutpat vel feugiat eu, scelerisque nec eros. Duis magna leo, ornare quis rhoncus vitae, molestie eu sem. Suspendisse commodo mi id maximus pulvinar. Nulla iaculis lacinia leo sed luctus. Maecenas ultricies leo eget nulla aliquam, quis luctus sapien molestie. Donec consectetur velit in suscipit tincidunt. Donec consequat tellus sit amet viverra egestas.

Sed luctus odio quis lorem consectetur, non porttitor elit congue. Maecenas tempor est ante, sed finibus quam placerat id. In dictum luctus magna, eget facilisis massa fringilla id. Curabitur commodo elit vel dapibus iaculis. Sed tristique nulla mi, id aliquam tortor sodales sit amet. Pellentesque non aliquam mauris. Pellentesque efficitur, erat sit amet sodales condimentum, ante lorem rhoncus arcu, vitae placerat dui velit quis diam. Sed at dictum nibh. Quisque et elit tellus. Phasellus eu pulvinar urna, at varius augue. Sed fermentum neque libero. Sed orci justo, ultrices quis risus vitae, egestas convallis lectus. Praesent rutrum est at elit posuere, id volutpat nisl rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque condimentum quis massa ac congue.

Mauris sodales porta ipsum. Praesent tincidunt consectetur orci nec eleifend. Etiam facilisis eros ac erat rutrum suscipit. Morbi non laoreet ipsum. Ut et porta odio. Vestibulum ac nisi blandit, elementum mauris quis, placerat enim. Sed hendrerit lacinia nisi in fermentum. Nullam condimentum accumsan leo eget scelerisque. Nullam posuere lorem nec nibh congue commodo.

Cras eu ornare ipsum. Cras sit amet eros id metus facilisis fringilla vitae in tortor. Nunc tincidunt sem eros, ac iaculis magna pretium eu. In dapibus luctus massa in imperdiet. In euismod sodales mauris et porta. Sed dapibus nunc sit amet arcu faucibus, in bibendum velit pharetra. Donec eu sollicitudin tortor. Sed ac iaculis felis, vitae euismod ipsum. Nunc molestie leo odio, vel ornare dui ultricies sed. Sed suscipit dignissim auctor.

Proin quis tincidunt ipsum, vel sollicitudin tortor. Nulla ullamcorper lobortis molestie. Aliquam at arcu tortor. Donec bibendum turpis sed leo dapibus, ut pellentesque mi sodales. Vestibulum quis diam mauris. Maecenas at est volutpat tellus gravida molestie id eu eros. Pellentesque aliquet congue risus at luctus.

Pellentesque eu nunc vitae velit varius scelerisque. Pellentesque eu porta enim. Vivamus quis neque nibh. Nunc sed lacus et ligula ornare sagittis. Aliquam dignissim consequat velit, ut porta neque pellentesque at. Sed eget finibus elit, vel venenatis eros. Nullam ornare iaculis arcu vitae consectetur. Suspendisse ut lobortis libero. Maecenas libero orci, mollis sed ligula et, lobortis congue libero. Donec aliquet neque non velit pretium euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Pellentesque cursus nec massa eget fringilla. Sed ut placerat tellus. Vestibulum et efficitur mauris, vel aliquam libero. Pellentesque fringilla urna et augue aliquet convallis eget in arcu. Sed vel tortor in tortor pretium commodo. Integer tincidunt finibus sem vitae varius. Sed viverra sagittis mi.

Aenean sit amet nisl ultrices, aliquet libero quis, elementum est. Etiam consequat, risus at dictum iaculis, risus urna bibendum justo, at efficitur risus felis sed urna. Donec varius vehicula urna, vitae feugiat ante lacinia a. Aenean tristique nisi vel magna venenatis efficitur. Vivamus porttitor arcu eget lectus scelerisque, eget porta elit tincidunt. Vivamus sollicitudin eget ligula vel dignissim. Quisque commodo sapien vitae felis ultrices elementum.

Etiam faucibus tincidunt nisl, sit amet gravida urna eleifend quis. Fusce euismod viverra tortor, at vehicula nulla accumsan quis. Duis convallis leo ut scelerisque faucibus. Nam sollicitudin finibus lectus sit amet condimentum. Nulla commodo vestibulum facilisis. Nunc hendrerit, massa id ultricies porta, enim tellus pulvinar sem, ut varius est massa eu justo. Aliquam suscipit, massa in faucibus tempor, erat est ultricies lorem, vel cursus mauris lectus nec nulla. Etiam sed nibh in turpis vestibulum luctus. Mauris porttitor at augue eu pharetra. Maecenas placerat mollis urna, eu scelerisque quam molestie sed. Proin at arcu arcu. Mauris nec est eget metus commodo interdum. Suspendisse facilisis turpis tellus, vitae venenatis nulla iaculis eu. Praesent nec tristique felis. Nulla facilisi.

Pellentesque varius et mauris sit amet dictum. Cras eleifend blandit viverra. Curabitur lorem felis, faucibus non posuere ac, ornare at ante. Mauris nec orci augue. Quisque tristique maximus orci at lacinia. In sodales tempor purus, sodales pharetra est suscipit vitae. Donec sed efficitur sem. Vivamus ut leo odio. Curabitur auctor urna ut egestas imperdiet. Nullam consequat accumsan libero, at commodo elit sollicitudin et.

Vestibulum risus urna, interdum et massa congue, gravida elementum nibh. Donec vitae scelerisque ante. Aliquam in diam vel purus tincidunt tincidunt lacinia eget nunc. Cras auctor elit libero. Suspendisse sed scelerisque odio. Cras ut euismod ex. Nam molestie euismod urna. Pellentesque molestie maximus dictum. Donec nisl lacus, vehicula nec lectus et, aliquet rhoncus libero. Vestibulum ultricies velit quis odio pulvinar, eu malesuada purus aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec faucibus nunc id pharetra egestas. Morbi elementum libero ut quam convallis vestibulum. Mauris cursus dui dolor, id vulputate ante convallis et. Praesent lobortis convallis cursus.

Nulla non tincidunt urna. Aliquam vel vestibulum urna. Nunc mattis, ante eleifend finibus ornare, sapien nulla facilisis ante, non mattis nisl risus quis dolor. Sed efficitur rhoncus quam sit amet tincidunt. Donec vitae imperdiet justo. Fusce eu ligula id nisi lobortis suscipit. Praesent iaculis ac nunc sed aliquet. Donec luctus condimentum dapibus. Morbi porta, arcu at aliquet pretium, purus tortor varius nisl, id tristique urna quam non enim. Nunc libero nisi, congue eget placerat vitae, ultricies nec arcu. Sed vulputate, erat in volutpat varius, urna metus elementum turpis, mollis posuere felis nulla ut erat. In faucibus, lectus quis posuere sagittis, urna nunc placerat mauris, eu pellentesque quam lorem id odio.');

INSERT INTO COMMENTS(author, comment, date, news_id) VALUES('Lex Luthor', 'Nice!.', '2021-09-09 12:03:03.516152', 3);
INSERT INTO COMMENTS(author, comment, date, news_id) VALUES('Lois Lane', 'So cool!', '2021-09-09 12:03:20.374154', 3);
INSERT INTO COMMENTS(author, comment, date, news_id) VALUES('Hal Jordan', 'That is interesting!', '2021-09-09 17:19:27.274124', 3);



INSERT INTO TOPIC_TAGS(id, topic_tags) VALUES(1, 'Lorem Ipsum'), (1, 'Artigo'), (1, 'Blog');
INSERT INTO TOPIC_TAGS(id, topic_tags) VALUES(2, 'Front End'), (2, 'Publicação'), (2, 'Internet');
INSERT INTO TOPIC_TAGS(id, topic_tags) VALUES(3, 'Angular'), (3, 'TypeScript'), (3, 'JavaScript'), (3, 'API RestFull');

